[package]
name = "blez"
version = "0.6.0"
description = "Asynchronous Bluetooth Low Energy using BlueZ"
readme = "README.md"
authors = [
    "Sebastian Urban <surban@surban.net>",
    "Attila Dusnoki <adusnoki@inf.u-szeged.hu>",
    "Ben Stern <bstern@fortian.com>",
]
repository = "https://github.com/surban/blez"
keywords = ["async", "bluetooth", "bluez", "ble", "gatt"]
categories = ["asynchronous", "hardware-support", "os::linux-apis"]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
dbus = { version = "0.9", features = ["futures"] }
dbus-tokio = "0.7"
dbus-crossroads = "0.3"
futures = "0.3"
pin-project = "1"
tokio = { version = "1", features = ["macros", "rt"] }
tokio-stream = "0.1"
hex = "0.4"
thiserror = "1"
lazy_static = "1"
uuid = { version = "0.8", features = ["v4"] }
strum = { version = "0.20", features = ["derive"] }
libc = "0.2"
custom_debug = "0.5"
log = "0.4"

[dev-dependencies]
crossterm = "0.19"
tokio = { version = "1", features = ["io-std", "io-util"] }
env_logger = "0.8"
