name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libdbus-1-dev
    - name: Check code formatting
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --examples --bins --quiet
    - name: Build documentation
      run: cargo doc --no-deps --quiet
    - name: Run tests
      run: cargo test --quiet
    - name: Code analysis
      run: cargo clippy --quiet
